grails-app/domain/com/hospital/Patient.groovy
package com.hospital

class Patient {

    String name
    String surname
    Date dateOfBirth
    String serviceRequired
    String diagnosis
    String contactNumber
    String email
    String source
    String keyword

    String nokName
    String nokSurname
    String nokRelation
    String nokContactNo
    String nokEmail

    String homeLocation
    String homePin
    String homeState
    String officeLocation
    String officePin
    String officeState

    String clinicalDetails
    String historyOfDisease
    String consultDoctor
    String hospitalName

    IABooking aiBooked
    IAConverted aiConverted
    String aiCancelled



    Date dateCreated
    Date dateModified
    User createdBy


    static constraints = {
        name(nullable: false, blank: false)
        surname(nullable: true, blank: true)
        dateOfBirth(nullable: true, blank: true)
        serviceRequired(nullable: true, blank: true)
        diagnosis(nullable: true, blank: true)
        contactNumber(nullable: true, blank: true)
        email(nullable: true, blank: true)
        source(nullable: true, blank: true)
        keyword(nullable: true, blank: true)
        nokName(nullable: true, blank: true)
        nokSurname(nullable: true, blank: true)
        nokRelation(nullable: true, blank: true)
        nokContactNo(nullable: true, blank: true)
        nokEmail(nullable: true, blank: true)
        homeLocation(nullable: true, blank: true)
        homePin(nullable: true, blank: true)
        homeState(nullable: true, blank: true)
        officeLocation(nullable: true, blank: true)
        officePin(nullable: true, blank: true)
        officeState(nullable: true, blank: true)
        clinicalDetails(nullable: true, blank: true)
        historyOfDisease(nullable: true, blank: true)
        consultDoctor(nullable: true, blank: true)
        hospitalName(nullable: true, blank: true)
        aiBooked(nullable: true, blank: true)
        aiConverted(nullable: true, blank: true)
        aiCancelled(nullable: true, blank: true)
        dateModified nullable: true, blank: true
    }
}

grails-app/controllers/com/hospital/DoctorController.groovy
package com.hospital

import grails.plugin.springsecurity.annotation.Secured

@Secured(["hasRole('hcp')"])
class DoctorController {
    def springSecurityService

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        User user = springSecurityService.getCurrentUser();
        List<Patient> patientList = IABooking.findAllByTherapistNameAndStatus(user, BookingStatus.ASSIGNED, params)*.patient
        Integer count = IABooking.countByTherapistNameAndStatus(user, BookingStatus.ASSIGNED)
        respond patientList, model:[patientInstanceCount: count]
    }

    def show(Patient patient) {
        PatientForDoctorVO patientInstance = new PatientForDoctorVO(patient)
        respond patientInstance, model: [patientInstance: patientInstance]
    }

    def start() {
        IABooking iaBooking = IABooking.get(params.aiBookingId)
        if (iaBooking) {
            iaBooking.status = BookingStatus.VISIT_STARTED
            DoctorVisit doctorVisit = new DoctorVisit();
            doctorVisit.iaBooking = iaBooking
            doctorVisit.hcp = springSecurityService.getCurrentUser();
            doctorVisit.visitStartTime = new Date()
            doctorVisit.save(flash: true, failOnError: true)
            render "ok"
        } else {
            return 'error'
        }
    }

    def stop() {
        IABooking iaBooking = IABooking.get(params.aiBookingId)
        if (iaBooking) {
            iaBooking.status = BookingStatus.VISIT_COMPLETED
            DoctorVisit doctorVisit = DoctorVisit.findByIaBooking(iaBooking)
            if (doctorVisit) {
                doctorVisit.visitEndTime = new Date();
            }
            render "ok"
        } else {
            return 'error'
        }
    }

    def finish() {
        IABooking iaBooking = IABooking.get(params.aiBookingId)
        if (iaBooking) {
            DoctorVisit doctorVisit = DoctorVisit.findByIaBooking(iaBooking)
            if (doctorVisit) {
                doctorVisit.comments = params.comment
            }
        }
        redirect action: 'index'
    }
}

grails-app/views/doctor/index.gsp
<%--
  Created by IntelliJ IDEA.
  User: dhanendra
  Date: 10/4/17
  Time: 11:26 PM
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
	<meta name="layout" content="main"/>
	<title>Doctor</title>
	<g:set var="entityName" value="Patient"/>
</head>
<body>
<div id="list-patient" class="content scaffold-list" role="main">
	<h1 class="header"><g:message code="default.list.label" args="[entityName]" /></h1>
	<g:if test="${flash.message}">
		<div class="message" role="status">${flash.message}</div>
	</g:if>
	<div class="card-panel">
		<table class="responsive-table highlight">
			<thead>
			<tr>
				<g:sortableColumn property="id" title="${message(code: 'patient.name.label', default: 'Pat_id')}" />

				<g:sortableColumn property="name" title="${message(code: 'patient.name.label', default: 'Name')}" />

				<g:sortableColumn property="surname" title="${message(code: 'patient.surname.label', default: 'Surname')}" />

				<g:sortableColumn property="homeLocatoin" title="${message(code: 'patient.serviceRequired.label', default: 'Address')}" />

				<g:sortableColumn property="serviceRequired" title="${message(code: 'patient.diagnosis.label', default: 'Service Required')}" />
			</tr>
			</thead>
			<tbody>
			<g:each in="${patientInstanceList}" status="i" var="patientInstance">
				<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					<td><g:link action="show" id="${patientInstance.id}">${fieldValue(bean: patientInstance, field: "id")}</g:link></td>

					<td>${fieldValue(bean: patientInstance, field: "name")}</td>

					<td>${fieldValue(bean: patientInstance, field: "surname")}</td>

					<td>${fieldValue(bean: patientInstance, field: "homeLocation")}</td>

					<td>${fieldValue(bean: patientInstance, field: "serviceRequired")}</td>
				</tr>
			</g:each>
			</tbody>
		</table>
	</div>
	<div class="pagination">
		<g:paginate total="${patientInstanceCount ?: 0}" />
	</div>
</div>
</body>
</html>

grails-app/views/doctor/show.gsp
<%--
  Created by IntelliJ IDEA.
  User: dhanendra
  Date: 18/3/17
  Time: 5:47 PM
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
	<meta name="layout" content="main"/>
	<title>Doctor</title>
	<g:set var="entityName" value="Doctor"/>
</head>
<body>
<a href="#show-patient" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
<div class="nav" role="navigation">
	<ul>
		<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
		<li><g:form controller="logout"><g:submitButton name="Logout">Logout</g:submitButton></g:form></li>
	</ul>
</div>
<div id="show-patient" class="content scaffold-show" role="main">
	<g:if test="${flash.message}">
		<div class="message" role="status">${flash.message}</div>
	</g:if>
	<div id="success-response" style="display: none">
		<div class="message" role="status" id="success-response-text"></div>
	</div>
	<ol class="property-list patient">

		<g:if test="${patientInstance?.name}">
			<li class="fieldcontain">
				<span id="name" class="property-label"><g:message code="patient.patient_name.label" default="Patient Name" /></span>

				<span class="property-value" aria-labelledby="name-label"><g:fieldValue bean="${patientInstance}" field="name"/></span>

			</li>
		</g:if>
		<g:if test="${patientInstance?.nokName}">
			<li class="fieldcontain">
				<span id="nokName" class="property-label"><g:message code="patient.nok_name.label" default="NOK Name" /></span>

				<span class="property-value" aria-labelledby="nokName"><g:fieldValue bean="${patientInstance}" field="nokName"/></span>

			</li>
		</g:if>
		<g:if test="${patientInstance?.homeLocation}">
			<li class="fieldcontain">
				<span id="homeLocation" class="property-label"><g:message code="patient.address.label" default="Address" /></span>

				<span class="property-value" aria-labelledby="homeLocation"><g:fieldValue bean="${patientInstance}" field="homeLocation"/></span>

			</li>
		</g:if>
		<g:if test="${patientInstance?.clinicalDetails}">
			<li class="fieldcontain">
				<span id="clinicalDetails" class="property-label"><g:message code="patient.clinical_details.label" default="Clinical Details" /></span>

				<span class="property-value" aria-labelledby="clinicalDetails"><g:fieldValue bean="${patientInstance}" field="clinicalDetails"/></span>

			</li>
		</g:if>
		<g:if test="${patientInstance?.historyOfDisease}">
			<li class="fieldcontain">
				<span id="historyOfDisease" class="property-label"><g:message code="patient.diagnosis.label" default="Diagnosis" /></span>

				<span class="property-value" aria-labelledby="historyOfDisease"><g:fieldValue bean="${patientInstance}" field="historyOfDisease"/></span>

			</li>
		</g:if>
		<g:if test="${patientInstance?.createdBy?.name}">
			<li class="fieldcontain">
				<span id="agent_name" class="property-label"><g:message code="patient.agent_name.label" default="Agent Name" /></span>

				<span class="property-value" aria-labelledby="agent_name">${patientInstance.createdBy.name}</span>

			</li>
		</g:if>
		<g:if test="${patientInstance?.visitTime}">
			<li class="fieldcontain">
				<span id="visitTime" class="property-label"><g:message code="patient.visit_time.label" default="Visit Time" /></span>

				<span class="property-value" aria-labelledby="visitTime"><g:fieldValue bean="${patientInstance}" field="visitTime"/></span>

			</li>
		</g:if>
		<g:remoteLink id="start-button" controller="doctor" action="start" params='["aiBookingId":"${patientInstance?.aiBookedId}"]' onSuccess="visitStarted()">Start</g:remoteLink>
		<g:remoteLink id="stop-button" style="display: none" controller="doctor" action="stop" params='["aiBookingId":"${patientInstance?.aiBookedId}"]'  onSuccess="showDialog()">Stop</g:remoteLink>
	</ol>
	<div id="id_commentBox" style="display: none">
		<div class="aligncenter">
			<g:form action="finish" >
				<fieldset class="finish">
					<input type="text" name="comment" placeholder="Comment"/>
					<input type="hidden" name="aiBookingId" value="${patientInstance?.aiBookedId}"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="submit" value="${message(code: 'default.button.Submit.label', default: 'Submit')}" />
				</fieldset>
			</g:form>
		</div>
	</div>
</div>
<script>
	function showDialog() {
		$("#id_commentBox").show();
		$("#stop-button").hide();
	}
	function visitStarted() {
		$("#success-response-text").html("Visit has started");
		$("#success-response").show();
		$("#start-button").hide();
		$("#stop-button").show();
	}
</script>
</body>
</html>